printWidth: 100
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
quoteProps: "consistent"
jsxSingleQuote: false
trailingComma: "es5"
bracketSpacing: true
bracketSameLine: false
arrowParens: "always"
requirePragma: false
insertPragma: false
proseWrap: "never"
htmlWhitespaceSensitivity: "css"
vueIndentScriptAndStyle: false
endOfLine: "lf"
embeddedLanguageFormatting: "auto"
